### ISSUE TITLE
Simple Question - Create an instance not using DI for Integration Testing

### ISSUE THREAD

**Issue by nhwilly** [IEvangelist/azure-cosmos-dotnet-repository#299]
Great library, thanks to everyone for this.

I am trying do some integration testing and load test data during the initialization of my xUnit WebApplicationFactory.  

At the point that I'm trying to load data, I don't have access to the Services collection.  Is there a simple way to just create an instance of IRepository<T> on the fly?

I've dug around and can't find anything.

TIA

**Comment by IEvangelist** [comment]
Sorry for the delay, been buried lately. Thank you for your kind words.

There isn't an easy way to do that, that is by design. For integration and load testing, you'd have to configure it for testing, with your test connections. When you call:

```cs
public void ConfigureServices(IServiceCollection services)
{
    services.AddCosmosRepository(
        options =>
        {
            options.CosmosConnectionString = "< test connection string >";
            options.ContainerId = "test-data-store";
            options.DatabaseId = "test";
        });
}
```

Make sure you're configuring this to use your test connections.
