### ISSUE TITLE
Creating a container with a different class

### ISSUE THREAD

**Issue by drma-dev** [IEvangelist/azure-cosmos-dotnet-repository#32]
I have defined a class and I am inserting an item in the container with another class (which inherits from it).

![image](https://user-images.githubusercontent.com/12803050/102924527-8565cf80-4470-11eb-9368-42209470d61f.png)

But the container is creating from the class I passed, not from the class I defined in the repository.

![image](https://user-images.githubusercontent.com/12803050/102924650-c1009980-4470-11eb-8a97-5c1dd3fd2492.png)

**Comment by drma-dev** [comment]
I saw that in the example a converter is used, but why is a type required in the repository, if that type is not respected.

**Comment by IEvangelist** [comment]
Hi @drma-dev - the type is the type of the instance, since `Item` is a concrete type, and there are no type parameters involved here - it uses the `.GetType()` function on the instance.

https://github.com/IEvangelist/azure-cosmos-dotnet-repository/blob/main/Microsoft.Azure.CosmosRepository/src/Item.cs#L56

The instance in your case is a `ProfileAddCommand`, so it correctly types this. Were you expecting it to be typed as `Profile`?

**Comment by drma-dev** [comment]
So, I created the repository based on the Profile class.

I'm using the ProfileAddCommand class, which inherits from Profile, just to avoid duplicating the attributes.

**Comment by drma-dev** [comment]
But talking about it, I saw another approach that I found interesting.

The type was merged into the Id, in the following format: 'type::id'

So, wouldn't it be more interesting to be like that? since it would allow you to create two items in the same collection and using the same id?

**Comment by IEvangelist** [comment]
This works as defined and as desired. Closing for now, we could always reopen this if need be, or if you're interesting in taking a stab at posting a PR. I would consider reviewing it.
