### ISSUE TITLE
Feature : Managed identity

### ISSUE THREAD

**Issue by PraveenValavan** [IEvangelist/azure-cosmos-dotnet-repository#56]
Thanks for the project!!
We want to access our database through managed Identity, when will it be possible ?

**Comment by IEvangelist** [comment]
I'm not sure I follow? Is there a way to use the existing .NET Cosmos DB SDK with managed identity now -- if so where are the details on that, it might be as easy as exposing a pass-thru?

**Comment by diredd** [comment]
Its 

> Hi @PraveenValavan
> I'm not sure I follow? Is there a way to use the existing .NET Cosmos DB SDK with managed identity now -- if so where are the details on that, it might be as easy as exposing a pass-thru?

This is great library, I am planning to use this in our application and have plans to use Managed Identity enabled between Function App and CosmosDB. Can you please suggest if there is a way to extend this library to support Managed Identities, or write custom ICosmosClientProvider provider and register instead of DefaultCosmosClientProvider.

It's not clear for me if Cosmos DB supports managed identity for reading data officially. But I got a sample function app access CosmosDB data using Managed Identity.

CosmosClient takes cosmosdb uri, and TokenCredential.

![image](https://user-images.githubusercontent.com/62980999/131324285-cc6e9382-a1f5-4f13-b620-21cffe589fd4.png)

[this link says its supported](https://docs.microsoft.com/en-us/azure/cosmos-db/managed-identity-based-authentication)
[but this says otherwise](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/tutorial-windows-vm-access-cosmos-db#:~:text=Cosmos%20DB%20does%20not%20natively%20support%20Azure%20AD,to%20the%20keys%20to%20the%20Cosmos%20DB%20account.)

**Comment by diredd** [comment]
Its 

> Hi @PraveenValavan
> I'm not sure I follow? Is there a way to use the existing .NET Cosmos DB SDK with managed identity now -- if so where are the details on that, it might be as easy as exposing a pass-thru?

This is great library, I am planning to use this in our application and have plans to use Managed Identity enabled between Function App and CosmosDB. Can you please suggest if there is a way to extend this library to support Managed Identities, or write custom ICosmosClientProvider provider and register instead of DefaultCosmosClientProvider.

It's not clear for me if Cosmos DB supports managed identity for reading data officially. But I got a sample function app access CosmosDB data using Managed Identity.

CosmosClient takes cosmosdb uri, and TokenCredential.

![image](https://user-images.githubusercontent.com/62980999/131324285-cc6e9382-a1f5-4f13-b620-21cffe589fd4.png)

[this link says its supported](https://docs.microsoft.com/en-us/azure/cosmos-db/managed-identity-based-authentication)
[but this says otherwise](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/tutorial-windows-vm-access-cosmos-db#:~:text=Cosmos%20DB%20does%20not%20natively%20support%20Azure%20AD,to%20the%20keys%20to%20the%20Cosmos%20DB%20account.)

**Comment by mumby0168** [comment]
Hi all @diredd @PraveenValavan @IEvangelist 

We can support this I will add it to the version milestone '2.4.0'.

**Comment by mumby0168** [comment]
Hi all please see PR #114 @diredd @PraveenValavan.
